### ISSUE TITLE
Additional svg element not documented, leads to unexpected issues

### ISSUE THREAD

**Issue by domsson** [svgdotjs/svg.js#553]
Apparently, svg.js not only creates the `svg` element within the given container, but an additional one on the same level as the container element. This additional `svg` has a dimension (`width="2"`) and some inline-styling (`opacity: 0; position: fixed; left: 100%; top: 100%; overflow: hidden;`).

I experienced two issues with this:
- I couldn't find this documented anywhere, the 'resulting markup' example doesn't show it. Without documentation, one might [think this is a bug](http://stackoverflow.com/questions/23879328/svg-js-creates-double-svgs/).
- When creating a full-screen (width/height 100%) `svg`, the additional `svg` will make for vertical scroll bars as the width of 2px and the fixed position will make for more than 100% size.

To fix the latter, changing `position: fixed` to `position: absolute` would work, but I assume `fixed` has been chosen for a reason? Using `absolute` did seem to work for me, but I'm not sure if it is safe to use. I would appreciate input on how to best handle this.

**Comment by Fuzzyma** [comment]
Actually no I cant think of a reason for the hidden svg to be fixed. I dont even know why it isnt completely offscreen.

Can you please add a jsfiddle showing the issue? You can also try to run the tests with your change and see if a test fails.

For the documentation: Yes I am aware of this. I just didnt find time to write it down. Ofc you can submit a PR to add it!

**Comment by Zearin** [comment]
> Apparently, svg.js not only creates the svg element within the given container, but an additional one on the same level as the container element. This additional svg has a dimension (width="2") and some inline-styling (opacity: 0; position: fixed; left: 100%; top: 100%; overflow: hidden;).

**Quick question:** _Why_ does SVG.js create this additional sibling?

**Comment by Fuzzyma** [comment]
To compute several stuff and create e.g. native SVG.Matrix

**Comment by Fuzzyma** [comment]
@wout can you pls verifiy that using position:absolute is okay?
Or we could use `right:100%;bottom:100%` instead which wont produce scrollbars

**Comment by wout** [comment]
Not quite sure, we've had some trouble with it in the past when users did something like `svg { ... !important; }`. But right/bottom sounds safe and we only need it to be `2px` x `2px`.

**Comment by dotnetCarpenter** [comment]
Seems to me that a hidden element (not `display:none;`) is achieved with `position:absolute;left:-99999px;` or more modern `transform:translateX(-99999px);`

**Comment by Fuzzyma** [comment]
svg transform is not allowed on `<svg>` tags so I feel unconfortable when we transform them with css instead. So I would go for the first suggestion.

**Comment by Fuzzyma** [comment]
@domsson can you confirm that the issue is fixed?

**Comment by domsson** [comment]
Sorry, took me a while to get back to this thread. I just tried with 2.5.2 and I'm still experiencing the scroll bar issue due to the additional `svg` element as can be seen here: https://jsfiddle.net/1khs0nwa/

However, I think I was mistaken in my original post when I said that I changed the additional element's `position` attribute - I just checked and saw that I did that for the main `svg` element. Setting that to `position: absolute` does get rid of the scroll bar in my example / fiddle.

**Comment by domsson** [comment]
Just tried with 2.5.2, still experiencing the scroll bar issue. However, it seems I was mistaken in my first post when I wrote that changing the additional `svg` element's `position` attribute would fix it - checking my code, it looks as if I set the main `svg` to `position: absolute`.

Compare: https://jsfiddle.net/1khs0nwa/1/ to https://jsfiddle.net/1khs0nwa/2/
